image: nginx:alpine

stages:
  - deploy

pages:
  stage: deploy

  script:
    - echo "Deploy"
    - cd public/
  artifacts:
    paths:
      - public/*  # Publie le répertoire public via GitLab Pages
  only:
    - main