# The Docker image that will be used to build your app
image: nginx:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "Deploying to /public"
    - cd public/.  
  artifacts:
    paths:
      - public
  only:
    - main