# The Docker image that will be used to build your app
image: alpine:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - cp -r * /usr/share/nginx/html/
  artifacts:
    paths:
      - public
  only:
    - main