# The Docker image that will be used to build your app
image: alpine:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - cp -r public/* /home
    - echo "Deployed to /home"
    - ls -la /home
    - ls
    - cd /home/public
    
  artifacts:
    paths:
      - public
  only:
    - main