# The Docker image that will be used to build your app
image: alpine:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "copying unused files"
    - mkdir -p /usr/share/nginx/html 
    - cp -r public/ /usr/share/nginx/hmtl
    - echo "Deploying to /public"
    - cd /usr/share/nginx/hmtl
    - ls -la
  artifacts:
    paths:
      - public
  only:
    - main