image: nginx:alpine

stages:
  - deploy

pages:
  stage: deploy

  script:
    - echo "Deploy"
    - cd public/
  artifacts:
    paths:
      - public/
      - public/js
      - public/css
      - public/assets/images
      - public/assets/face-animation-light
      - public/assets/face-animation-dark
      - public/assets/icons
  only:
    - main