# The Docker image that will be used to build your app
image: alpine:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    # Vérifie si le répertoire "public" existe, sinon le crée
    - mkdir -p public
    # Copie tous les fichiers dans "public"
    - cp -r * public/
  artifacts:
    paths:
      - public
  only:
    - main