# The Docker image that will be used to build your app
image: alpine:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "Deploying to /public"
    - ls
    - cd public/
    - ls
    - cd assets/
    - ls
    
    
  artifacts:
    paths:
      - public
  only:
    - main