# The Docker image that will be used to build your app
image: alpine:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "copying unused files"
    - cp -r public/ public/html/
    - echo "Deploying to /public"
    - cd public/html
    - ls -la
  artifacts:
    paths:
      - public
  only:
    - main